#ifndef ZMQWORKERS_GLOBAL_H
#define ZMQWORKERS_GLOBAL_H

#include <QtGlobal>

#if defined(ZMQWORKERS_LIBRARY)
#  define ZMQWORKERSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZMQWORKERSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZMQWORKERS_GLOBAL_H
